const assert=require('node:assert/strict');
const api=require('./api/index.js');
const code='A'.repeat(32);
process.env.PETUGAS_JSON=JSON.stringify([{id:'P1',name:'Petugas 1',active:true,hash:api._test.sha256(code)}]);
assert.equal(api._test.authenticate(code).id,'P1');
assert.throws(()=>api._test.authenticate('1234'));
assert.throws(()=>api._test.authenticate('B'.repeat(32)));
const report={reportId:'12345678-1234-1234-1234-123456789abc',ids:Array.from({length:9},(_,i)=>'drive_file_id_'+i),name:'Rumah Ahmad'};
assert.equal(api._test.validateReport(report,{id:'P1'}),'Rumah Ahmad');
assert.throws(()=>api._test.validateReport({...report,name:''},{id:'P1'}));
process.env.STORAGE_DRIVER='s3';
process.env.S3_ENDPOINT='https://s3.natanet.my.id';
process.env.S3_REGION='ap-southeast-3a';
process.env.S3_BUCKET='takara';
process.env.S3_ACCESS_KEY_ID='test-access';
process.env.S3_SECRET_ACCESS_KEY='test-secret';
assert.equal(api._test.storageDriver(),'s3');
assert.equal(api._test.s3Config().forcePathStyle,true);
const objectIds=api._test.reserveObjectIds();
assert.equal(objectIds.length,9);
assert.equal(new Set(objectIds).size,9);
assert.ok(objectIds.every(id=>id.startsWith('obj_')));
assert.equal(api._test.isObjectReport({...report,ids:objectIds}),true);
assert.equal(api._test.objectKey(report.reportId,'manifest.json'),'laporan/'+report.reportId+'/manifest.json');
console.log('PASS: Vercel auth hash and report validation');
(async()=>{
  let status=0,response;
  await api({method:'POST',headers:{'content-type':'application/json'},body:{action:'reserve',code}},{setHeader(){},status(value){status=value;return this;},json(value){response=value;return value;}});
  assert.equal(status,200);assert.equal(response.ok,true);assert.equal(response.ids.length,9);assert.ok(response.ids.every(id=>id.startsWith('obj_')));
  console.log('PASS: Object Storage reserve routing');
  const meta=Buffer.from(JSON.stringify({...report,action:'photo',slot:0})).toString('base64url');
  await api({method:'POST',headers:{'content-type':'application/octet-stream','x-desil-code':'1234','x-desil-meta':meta},body:Buffer.from([0xff,0xd8,0xff,0xd9])},{setHeader(){},status(value){status=value;return this;},json(value){response=value;return value;}});
  assert.equal(status,401);assert.equal(response.ok,false);
  console.log('PASS: Vercel binary upload request parsing');
})().catch(error=>{console.error(error);process.exitCode=1;});
